
@startuml

abstract class GraphInterface {
    +{abstract} GetReferencedCells(): vector<Position>
    +{abstract} GetDependentCells(): vector<Position>
    +{abstract} AddDependentCell(in pos: Position)
    +{abstract} DeleteDependentCell(in pos: Position)
    +{abstract} HasCircularDependency(inout visitedCells: unordered_set<CellInterface*>&, \nin currentCell: Position, in referencedCells: vector<Position>)
}

abstract class Impl {
    +Impl(in sheet: SheetInterface)
    +{abstract} GetValue(in getCellValueCallback: function): Value
    +{abstract} GetText(): string
    +{abstract} InvalidateCache()

    -sheet_: SheetInterface&
    -dependentCells_: unordered_set<Position>
}

class Impl extends GraphInterface

class EmptyImpl {
}

class TextImpl {
    +TextImpl(in text: string)
    +Set(in text: string)
    -value_: string
}

class FormulaImpl {
    +FormulaImpl(in sheet: SheetInterface, in text: string)
    +Set(in text: string)

    -formula_: unique_ptr<FormulaInterface>
    -cache_: optional<CellInterface::Value>
}

class EmptyImpl implements Impl
class TextImpl implements Impl
class FormulaImpl implements Impl

@enduml
