
@startuml
!include cellImpl.puml

abstract class CellInterface {
    +{abstract} Set(in text: string)
    +{abstract} GetValue(in getCellValueCallback: function): Value
    +{abstract} GetText(): string
    +{abstract} GetReferencedCells(): vector<Position>
}

class Cell {
    +Cell()
    +Clear()
    +GetDependentCells(): vector<Position>
    +AddDependentCell(in pos: Position)
    +DeleteDependentCell(in pos: Position)
    +InvalidateCache()
    -cell_: Impl*
}

class Cell extends CellInterface
Cell *-r- Impl

@enduml
