
@startuml
!include expression.puml

class FormulaAST {
    +Execute(in getCellValueCallback: function): double
    +Print(inout os: ostream)
    +PrintFormula(inout os: ostream)
    -rootExpr_: Expr
}

FormulaAST *-r- Expr

@enduml
