
@startuml

package FormulaASTUML {
    !include formulaAst.puml
}

abstract class FormulaInterface {
    +{abstract} Evaluate(in sheet: SheetInterface): Value
    +{abstract} GetExpression(): string
    +{abstract} GetReferencedCells(): vector<Position>
}

class Formula {
    +Formula(in expression: string)
    -ast_: FormulaAST
    -referencedCells_: vector<Position>
}

class Formula implements FormulaInterface
Formula *-r- FormulaAST

@enduml
