
@startuml

abstract class SheetInterface {
    +{abstract} SetCell(in pos: Position, in text: string)
    +{abstract} GetCell(in pos: Position): CellInterface*
    +{abstract} GetCell(in pos: Position) const: CellInterface*
    +{abstract} ClearCell(in pos: Position)
    +{abstract} GetPrintableSize(): Size
    +{abstract} PrintValues(inout os: ostream)
    +{abstract} PrintTexts(inout os: ostream)
    +{abstract} GetCellValue(in str: string_view): double
}

class Sheet {
    -cells_: vector<vector<CellInterface*>>>
    -HasCircularDependency(in posToUpdate: Position, in referencedCells: vector<Position>): bool
}

class Sheet extends SheetInterface

@enduml
